### ISSUE TITLE
Left/Right Arrows, 1/2, 4/6 to Vote

### ISSUE THREAD

**Issue by Jay4242** [HenryLoenwind/sdcompare#1]
Great tool.  I was thinking it might make it even easier to vote if key combinations could select the winning image.
Left & Right arrows seem natural.  Also maybe 1 & 2 keys for 1st or 2nd photo.  Also 4 & 6, since that's the left and right arrows on the numpad.

**Comment by HenryLoenwind** [comment]
Makes sense and I planned to add it already---I just keep forgetting it ;)

**Comment by HenryLoenwind** [comment]
Implemented. Will be in the next version.

**Comment by HenryLoenwind** [comment]
Implemented in version 2.

Note that I used 1+3 for "exclude", so only 4+6 and left+right are for "like".
